### ISSUE TITLE
Change console log while generating derivatives

### ISSUE THREAD

**Issue by elotroalex** [minicomp/wax_tasks#19]
**Describe the bug**
While generating, the message should indicate that the process is happening, rather than wait for it to finish. This is important for big images.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mnyrop** [comment]
Added a progress bar in v 1.0.0 on `refactor` branch
