### ISSUE TITLE
Add error message for cases where number of images and number of rows don't match

### ISSUE THREAD

**Issue by elotroalex** [minicomp/wax_tasks#20]
**Is your feature request related to a problem? Please describe.**
This happened twice to me already in completely different contexts, so I'm guessing it will be a relatively common problem. Terminal spits out a nil value error. We might be able to be more specific about the nature of the error so producers can quickly address.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mnyrop** [comment]
Adding a warning instead of an error, because there are times when this would be OK 
(e.g. Sudan Photo has some records where there is no image /  it tells users to visit the archive instead)

**Comment by mnyrop** [comment]
There is now a warning (not error) for when an item doesn't have a corresponding record

**Comment by elotroalex** [comment]
good times
