### ISSUE TITLE
Simple derivative generation is slow; still makes images in memory even if file path exists.

### ISSUE THREAD

**Issue by mnyrop** [minicomp/wax_tasks#30]
This would require a decent amount of work to refactor but would be worth it. 

### Current behavior: 
Skips writing derivative (in memory) to disk if target file already exists

### Desired behavior: 
Should skip creating derivative *at all* if target file already exists. 
This means collections need to know *all** of their target derivative paths in advance.
If successful, derivative tasks would take the same amount of time the first time they are run, but would be exponentially quicker when rerun.

**Comment by pbinkley** [comment]
Is this still the case? I thought it was related to this comment: https://github.com/minicomp/wax_iiif/blob/master/lib/wax_iiif/builder.rb#L249 . But I find that ```info.json``` **is** being detected, and when it exists ```ImageVariant``` is never instantiated and so the source image is never opened. I think this issue can be closed, unless there are cases I'm not seeing.

**Comment by mnyrop** [comment]
Hi @pbinkley just working through your tickets/comments now. I edited this issue title to be more specific, since this *should* only be an issue for simple image derivatives (and not IIIF).

The culprits are here:

https://github.com/minicomp/wax_tasks/blob/master/lib/wax_tasks/asset.rb#L27

and here:

https://github.com/minicomp/wax_tasks/blob/master/lib/wax_tasks/collection/images.rb#L63

where essentially the derivatives get made in memory with `Derivative.new()`, and only **after** that does it run `next if File.exist? path` to skip writing it to a file. But unfortunately by that point ImageMagick has already done all the heavy lifting.
