### ISSUE TITLE
Custom variants are not being generated

### ISSUE THREAD

**Issue by pbinkley** [minicomp/wax_tasks#48]
Custom variant image sizes specified in ```_config.yml``` for a given collection are not being generated.

**To Reproduce**
- In out-of-the-box wax, add custom variant sizes to a collection in ```_config.yml```, following the example in the [sample site](https://github.com/minicomp/wax_tasks/blob/403b4c1f02341f2722df7b905a584c88b37e8cc1/spec/sample_site/_config.yml#L19-L21)
- render the iiif derivatives with ```bundle exec rake wax:derivatives:iiif```

**Expected behavior**
An image such as ```obj12_00``` ought to have the following full-region images in ```img/derivatives/iiif/images/obj12_00/full/```: ```50, 250, 1400, full```. Instead, only the default sizes are found: ```250, full```.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser: n/a
 - Version: n/a

**Additional context**
This is an important feature to make Wax IIIF images fully reusable, since Universal Viewer always requests ```90,``` thumbnails. An item without ```90,``` thumbnails always looks broken in UV.

**Comment by mnyrop** [comment]
thanks for this. i'll poke around later today.

**Comment by mnyrop** [comment]
Hi @pbinkley ! I *just* got around to working on this. Any interest in testing it out with a use case of yours before I cut a release? You *should* be able to generate custom variants now if you change your Gemfile to use 

`gem 'wax_tasks', git: 'https://github.com/minicomp/wax_tasks.git', branch: 'v1.0.3'`

**Comment by pbinkley** [comment]
It works! I added a 90-width thumbnail to an instance of the wax_theme demo site:

```
    images:
      source: 'raw_images/qatar' # path to the directory of images within `_data`
      variants:
         uvthumb: 90
```

And the 90-width images were created properly by ```wax:derivatives:iiif```:

```
$ identify img/derivatives/iiif/images/obj1/full/90,/0/default.jpg 
img/derivatives/iiif/images/obj1/full/90,/0/default.jpg JPEG 90x61 90x61+0+0 8-bit sRGB 4255B 0.000u 0:00.000
```

I had to upgrade rake in ```wax_theme.gemspec``` to agree with version 13 specified in the new release:

```
spec.add_development_dependency 'rake', '~> 13.0'
``` 
When this release is out, I'll update ```postwax``` to use this method to create the 90-width thumbnails that Universal Viewer requires. Thanks for the fix!

**Comment by pbinkley** [comment]
BTW I realized I never posted an issue to UV about its behavior. I've done that now: https://github.com/UniversalViewer/universalviewer/issues/739
