### ISSUE TITLE
Remove layout population from wax:pages

### ISSUE THREAD

**Issue by dnoneill** [minicomp/wax_tasks#82]
**Is your feature request related to a problem? Please describe.**
Putting the layout in the front matter of a wax page is unnecessary since it is required to put in the _config.yml file and Jekyll will auto populate the layout from the _config.yml file. If you change it in the _config.yml file you have to reprocess all your pages file, which is unnecessary extra work for the user.

**Describe the solution you'd like**
Remove the piece of code that puts the layout in the front matter of every wax page.

**Describe alternatives you've considered**
There could be a setting that will put it in the front matter, but this should not be the default.

**Additional context**
Line 15
https://github.com/minicomp/wax/blame/e4dcaa10a28b427cd502ac960b8943952805ed7d/_qatar/obj10.md

**Comment by mnyrop** [comment]
Going through old tickets. I tried this out, but Jekyll does not implicitly pull in collection `layout` values from the config – they need to be in each page or set through [front-matter defaults](https://jekyllrb.com/docs/configuration/front-matter-defaults) which is a lot to ask for most users.

That said, you can just remove or comment out the `layout` line in the config...? (https://github.com/minicomp/wax/blob/f680acfbe30eb0dd801ec3df87e154b9b813ea68/_config.yml#L65). It's not a required field and it won't put anything there if there isn't a value set—there's no internal default.
