### ISSUE TITLE
Create Rake Task for creating PDF derivatives

### ISSUE THREAD

**Issue by dnoneill** [minicomp/wax_tasks#85]
**Is your feature request related to a problem? Please describe.**
I am trying to hook WAX up with GitHub actions so you can create derivatives via GitHub and don't have to download the repo. The problem I am running into is splitting PDFs doesn't work on GitHub actions using an Ubuntu machine and if you use a Mac to create the derivatives it takes twice as long to create the derivatives. What I would like to do is split the images on a Mac and then create the derivatives on an Ubuntu machine. I thought I would get away with running a ruby script that imported the wax_tasks library and run the script but it looks like all the methods are made private or something because they are not showing up as a method I can run using the library.

**Describe the solution you'd like**
A rake task to create the image derivatives.

**Describe alternatives you've considered**
Making the methods public to use when importing the library to ruby.

**Additional context**
n/a

**Comment by mnyrop** [comment]
I don't think this is in scope for the project. Wax_tasks uses ghostscript for this; it would probably be much easier for you to write a small bash/ruby script (you could use ghostscript as well but don't have to) instead of wax_tasks which is overkill for the job.
